"""Sync with database schema

Revision ID: 80a88b09045c
Revises: 
Create Date: 2024-07-02 19:04:24.454827

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '80a88b09045c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artista', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=64),
               nullable=True)

    with op.batch_alter_table('cancion', schema=None) as batch_op:
        batch_op.alter_column('titulo',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=128),
               nullable=True)
        batch_op.alter_column('album',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=128),
               existing_nullable=True)

    with op.batch_alter_table('disco', schema=None) as batch_op:
        batch_op.alter_column('titulo',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=128),
               nullable=True)

    with op.batch_alter_table('suscriptor', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=64),
               nullable=True)
        batch_op.alter_column('apellido',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=64),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=128),
               nullable=True)
        batch_op.drop_index('email')
        batch_op.create_index(batch_op.f('ix_usuario_email'), ['email'], unique=True)

    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.alter_column('titulo',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=128),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.alter_column('titulo',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuario_email'))
        batch_op.create_index('email', ['email'], unique=True)
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('apellido',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('suscriptor', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('disco', schema=None) as batch_op:
        batch_op.alter_column('titulo',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('cancion', schema=None) as batch_op:
        batch_op.alter_column('album',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('titulo',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('artista', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
